=== Alicia115/Lenguaje_de_Marcas/U1_Introducción/XSD - PRUEBAS CLASE/series.xsd
<?xmlversion="1.0"encoding="UTF-8"?>
<xs:schema
xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

    <xs:element name="serie">

        <xs:complexType>
            <xs:sequence>
                <xs:element name="temporada" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha_inicio" type="xs:date"/>
                            <xs:element name="fecha_final" type="xs:date"/>  
                            <xs:element name="capitulos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="capitulo" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="fecha_emision" type="xs:string"/>
                                                    <xs:element name="titulo" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType> 
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>                     
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    
    </xs:element>


</xs:schema>

=== Alicia115/Lenguaje_de_Marcas/U1_Introducción/XSD - PRUEBAS CLASE/series.xml
<?xml version="1.0" encoding="utf-8"?>

<serie
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="series.xsd">
    <temporada>
        <fecha_inicio>2020-01-20</fecha_inicio>
        <fecha_final></fecha_final>
        <capitulos>
            <capitulo>
                <titulo></titulo>
                <fecha_emision></fecha_emision>
            </capitulo>
            <capitulo>
                <titulo></titulo>
                <fecha_emision></fecha_emision>
            </capitulo>
        </capitulos>

    </temporada>

    <temporada>
    
    
    </temporada>

</serie>
